### ISSUE TITLE
As a user, I can see a menu icon on the fab button

### ISSUE THREAD

**Issue by babacarcissedia** [nushen96/portfolio-v2#3]
# Scope
Right now it is displaying a plus (+) icon which can be confusing
![image](https://user-images.githubusercontent.com/17571380/126691132-a4de4c33-53a8-4159-bddd-514876ba555f.png)

# Acceptance
See title

**Comment by nushen96** [comment]
I designed it as an action button. They generally have a plus icon right?

**Comment by babacarcissedia** [comment]
I think I found few case where it was a plus but I don't think that's a good UX. hamburber menu seems more appropriate to me

**Comment by nushen96** [comment]
You might be right. I will think about it. Thanks for the feedback.

**Comment by nushen96** [comment]
Turns out you were right 456256825c6dafb7f74ee71ed42778b44673dafb
