### ISSUE TITLE
As a developer, I shouldn't see credentials in the source code

### ISSUE THREAD

**Issue by babacarcissedia** [nushen96/portfolio-v2#5]
# Scope
![image](https://user-images.githubusercontent.com/17571380/126787560-f72ec9ab-55ba-4fd6-b72b-3e8ed36d3826.png)

# Technical
https://docs.netlify.com/configure-builds/environment-variables/

**Comment by nushen96** [comment]
Fixed with [a43aad5](https://github.com/nushen96/portfolio-v2/commit/a43aad598411e171e40619b2ff7214c21c98609d)
